### ISSUE TITLE
Library version used in phpinfo

### ISSUE THREAD

**Issue by remicollet** [wxphp/wxphp#101]
php_info_print_table_row(2, "wxWidgets Version", PHP_WXWIDGETS_VERSION);

Shouln't this use wxVERSION_STRING ? e.g.

	php_info_print_table_row(2, "Library Version", wxVERSION_STRING);

**Comment by jgmdev** [comment]
You are right! thats why I got an error message when uploading to pecl saying me that the source version was different from the package version and I had to change from 3.0.2 to 3.0.2.0. I didn't knew that constant was used as the extension version by default, instead I used PHP_WXWIDGETS_EXTVER, will fix. Thanks!

**Comment by remicollet** [comment]
Yes, on upload, PECL web-ui check for PHP_foo_VERSION (standardized macro name) to match the actual version (forgetting to change it was a so common error !).

So, PHP_WXWIDGETS_VERSION should be the extrension version, and then PHP_WXWIDGETS_EXTVER could be drop.

**Comment by remicollet** [comment]
nice, thanks
