### ISSUE TITLE
Error "error: expected class-name before '{' token" when building on Ubuntu 14.04

### ISSUE THREAD

**Issue by halfer** [wxphp/wxphp#109]
I've been following the [Linux build](https://github.com/wxphp/wxphp/wiki/building-on-linux) document, and have persisted for some time to investigate various errors, and have hit a road block. I'm on Ubuntu 14.04 LTS.

Here's the deps I've installed:

    sudo apt-get install php5-dev
    sudo apt-get install libwebkitgtk-dev
    sudo apt-get install libgconf2-dev
    sudo apt-get install libsdl1.2-dev

    # Not sure which version to use, trying 3
    sudo apt-get install libgtk-3-dev

    # For GStreamer, seems required
    sudo apt-get install libjpeg-dev libgconf2-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev

I've got this far:

    phpize
    ./configure

However, `make` fails:

	/bin/bash /development/GuestMonitor/wxphp/libtool --mode=compile g++  -I. -I/development/GuestMonitor/wxphp -DPHP_ATOM_INC -I/development/GuestMonitor/wxphp/include -I/development/GuestMonitor/wxphp/main -I/development/GuestMonitor/wxphp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/development/GuestMonitor/wxphp/includes -I/development/GuestMonitor/wxphp/wxWidgets-build/lib/wx/include/gtk3-unicode-static-3.0 -I/development/GuestMonitor/wxphp/wxWidgets-build/include/wx-3.0 -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12  -DHAVE_CONFIG_H  -g -O2 -Iincludes -I/development/GuestMonitor/wxphp/wxWidgets-build/lib/wx/include/gtk3-unicode-static-3.0 -I/development/GuestMonitor/wxphp/wxWidgets-build/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -D__WXGTK__ -pthread -pthread -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12   -c /development/GuestMonitor/wxphp/src/app.cpp -o src/app.lo 
	libtool: compile:  g++ -I. -I/development/GuestMonitor/wxphp -DPHP_ATOM_INC -I/development/GuestMonitor/wxphp/include -I/development/GuestMonitor/wxphp/main -I/development/GuestMonitor/wxphp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/development/GuestMonitor/wxphp/includes -I/development/GuestMonitor/wxphp/wxWidgets-build/lib/wx/include/gtk3-unicode-static-3.0 -I/development/GuestMonitor/wxphp/wxWidgets-build/include/wx-3.0 -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12 -DHAVE_CONFIG_H -g -O2 -Iincludes -I/development/GuestMonitor/wxphp/wxWidgets-build/lib/wx/include/gtk3-unicode-static-3.0 -I/development/GuestMonitor/wxphp/wxWidgets-build/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -D__WXGTK__ -pthread -pthread -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12 -c /development/GuestMonitor/wxphp/src/app.cpp  -fPIC -DPIC -o src/.libs/app.o
	/bin/bash /development/GuestMonitor/wxphp/libtool --mode=compile g++  -I. -I/development/GuestMonitor/wxphp -DPHP_ATOM_INC -I/development/GuestMonitor/wxphp/include -I/development/GuestMonitor/wxphp/main -I/development/GuestMonitor/wxphp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/development/GuestMonitor/wxphp/includes -I/development/GuestMonitor/wxphp/wxWidgets-build/lib/wx/include/gtk3-unicode-static-3.0 -I/development/GuestMonitor/wxphp/wxWidgets-build/include/wx-3.0 -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12  -DHAVE_CONFIG_H  -g -O2 -Iincludes -I/development/GuestMonitor/wxphp/wxWidgets-build/lib/wx/include/gtk3-unicode-static-3.0 -I/development/GuestMonitor/wxphp/wxWidgets-build/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -D__WXGTK__ -pthread -pthread -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12   -c /development/GuestMonitor/wxphp/src/references.cpp -o src/references.lo 
	libtool: compile:  g++ -I. -I/development/GuestMonitor/wxphp -DPHP_ATOM_INC -I/development/GuestMonitor/wxphp/include -I/development/GuestMonitor/wxphp/main -I/development/GuestMonitor/wxphp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/development/GuestMonitor/wxphp/includes -I/development/GuestMonitor/wxphp/wxWidgets-build/lib/wx/include/gtk3-unicode-static-3.0 -I/development/GuestMonitor/wxphp/wxWidgets-build/include/wx-3.0 -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12 -DHAVE_CONFIG_H -g -O2 -Iincludes -I/development/GuestMonitor/wxphp/wxWidgets-build/lib/wx/include/gtk3-unicode-static-3.0 -I/development/GuestMonitor/wxphp/wxWidgets-build/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -D__WXGTK__ -pthread -pthread -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12 -c /development/GuestMonitor/wxphp/src/references.cpp  -fPIC -DPIC -o src/.libs/references.o
	/bin/bash /development/GuestMonitor/wxphp/libtool --mode=compile g++  -I. -I/development/GuestMonitor/wxphp -DPHP_ATOM_INC -I/development/GuestMonitor/wxphp/include -I/development/GuestMonitor/wxphp/main -I/development/GuestMonitor/wxphp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/development/GuestMonitor/wxphp/includes -I/development/GuestMonitor/wxphp/wxWidgets-build/lib/wx/include/gtk3-unicode-static-3.0 -I/development/GuestMonitor/wxphp/wxWidgets-build/include/wx-3.0 -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12  -DHAVE_CONFIG_H  -g -O2 -Iincludes -I/development/GuestMonitor/wxphp/wxWidgets-build/lib/wx/include/gtk3-unicode-static-3.0 -I/development/GuestMonitor/wxphp/wxWidgets-build/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -D__WXGTK__ -pthread -pthread -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12   -c /development/GuestMonitor/wxphp/src/appmanagement.cpp -o src/appmanagement.lo 
	libtool: compile:  g++ -I. -I/development/GuestMonitor/wxphp -DPHP_ATOM_INC -I/development/GuestMonitor/wxphp/include -I/development/GuestMonitor/wxphp/main -I/development/GuestMonitor/wxphp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/development/GuestMonitor/wxphp/includes -I/development/GuestMonitor/wxphp/wxWidgets-build/lib/wx/include/gtk3-unicode-static-3.0 -I/development/GuestMonitor/wxphp/wxWidgets-build/include/wx-3.0 -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12 -DHAVE_CONFIG_H -g -O2 -Iincludes -I/development/GuestMonitor/wxphp/wxWidgets-build/lib/wx/include/gtk3-unicode-static-3.0 -I/development/GuestMonitor/wxphp/wxWidgets-build/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -D__WXGTK__ -pthread -pthread -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12 -c /development/GuestMonitor/wxphp/src/appmanagement.cpp  -fPIC -DPIC -o src/.libs/appmanagement.o
	In file included from /development/GuestMonitor/wxphp/src/appmanagement.cpp:19:0:
	/development/GuestMonitor/wxphp/includes/ctrl.h:4128:38: error: expected class-name before '{' token
	 class wxWebView_php: public wxWebView{
		                              ^
	In file included from /development/GuestMonitor/wxphp/src/appmanagement.cpp:25:0:
	/development/GuestMonitor/wxphp/includes/events.h:2767:48: error: expected class-name before '{' token
	 class wxWebViewEvent_php: public wxWebViewEvent{
		                                        ^
	/development/GuestMonitor/wxphp/includes/events.h: In constructor 'wxWebViewEvent_php::wxWebViewEvent_php()':
	/development/GuestMonitor/wxphp/includes/events.h:2770:23: error: class 'wxWebViewEvent_php' does not have any field named 'wxWebViewEvent'
	  wxWebViewEvent_php():wxWebViewEvent(){}
		               ^
	/development/GuestMonitor/wxphp/includes/events.h: In constructor 'wxWebViewEvent_php::wxWebViewEvent_php(wxEventType, int, wxString, wxString)':
	/development/GuestMonitor/wxphp/includes/events.h:2771:91: error: class 'wxWebViewEvent_php' does not have any field named 'wxWebViewEvent'
	  wxWebViewEvent_php(wxEventType type, int id, const wxString href, const wxString target):wxWebViewEvent(type, id, href, target){}
		                                                                                   ^
	In file included from /development/GuestMonitor/wxphp/src/appmanagement.cpp:48:0:
	/development/GuestMonitor/wxphp/includes/webview.h: At global scope:
	/development/GuestMonitor/wxphp/includes/webview.h:25:60: error: expected class-name before '{' token
	 class wxWebViewHistoryItem_php: public wxWebViewHistoryItem{
		                                                    ^
	/development/GuestMonitor/wxphp/includes/webview.h: In constructor 'wxWebViewHistoryItem_php::wxWebViewHistoryItem_php(const wxString&, const wxString&)':
	/development/GuestMonitor/wxphp/includes/webview.h:28:71: error: class 'wxWebViewHistoryItem_php' does not have any field named 'wxWebViewHistoryItem'
	  wxWebViewHistoryItem_php(const wxString& url, const wxString& title):wxWebViewHistoryItem(url, title){}
		                                                               ^
	/development/GuestMonitor/wxphp/includes/webview.h: At global scope:
	/development/GuestMonitor/wxphp/includes/webview.h:62:52: error: expected class-name before '{' token
	 class wxWebViewHandler_php: public wxWebViewHandler{
		                                            ^
	/development/GuestMonitor/wxphp/includes/webview.h: In constructor 'wxWebViewHandler_php::wxWebViewHandler_php(const wxString&)':
	/development/GuestMonitor/wxphp/includes/webview.h:65:47: error: class 'wxWebViewHandler_php' does not have any field named 'wxWebViewHandler'
	  wxWebViewHandler_php(const wxString& scheme):wxWebViewHandler(scheme){}
		                                       ^
	/development/GuestMonitor/wxphp/includes/webview.h: At global scope:
	/development/GuestMonitor/wxphp/includes/webview.h:99:66: error: expected class-name before '{' token
	 class wxWebViewArchiveHandler_php: public wxWebViewArchiveHandler{
		                                                          ^
	/development/GuestMonitor/wxphp/includes/webview.h: In constructor 'wxWebViewArchiveHandler_php::wxWebViewArchiveHandler_php(const wxString&)':
	/development/GuestMonitor/wxphp/includes/webview.h:102:54: error: class 'wxWebViewArchiveHandler_php' does not have any field named 'wxWebViewArchiveHandler'
	  wxWebViewArchiveHandler_php(const wxString& scheme):wxWebViewArchiveHandler(scheme){}
		                                              ^
	make: *** [src/appmanagement.lo] Error 1

I should be very happy to help improve the documentation to make building a painless process - I've spent several hours on this, and still not compiled. If PHP modules can be created for popular distros, and those distros requested to add the module to their repos, that would also help a great deal.

Thank you for your efforts on this project, and for any light you can shed on this particular issue.

**Comment by halfer** [comment]
Aha, this [has been asked before!](https://github.com/wxphp/wxphp/issues/102). Apologies for the duplicate.

**Comment by jgmdev** [comment]
Glad you where able to solve the issue, It would certainly be nice to have wxphp builds on linux distros, I think it was added to fedora by @remicollet Now what I have to worry is about finishing the new code generator or modifying current one in order to support soon to be released PHP 7, once PHP 7 hits the distro repositories wxPHP will not work until it is ported to it.

**Comment by halfer** [comment]
Yes, that certainly sounds more important @jgmdev! My project is only low priority, in any case - a mix of playing with something cool and a couple of utilities.
