### ISSUE TITLE
Automatic refresh on Ubuntu, not on Win7

### ISSUE THREAD

**Issue by davekimble2** [wxphp/wxphp#117]
This test app should make the squares turn red if they are dragged through.
It works OK on Ubuntu 14.04, but not on Ubuntu > VirtualBox > Win7
Win7 needs the Refresh() line, Ubuntu doesn't.

Why is it so?

```
<?php
$frame = new wxFrame(null, wxID_TOP, "Test", wxDefaultPosition, new wxSize(700, 300));
$frame->SetBackgroundColour(wxBLACK);
$frame->Connect(wxEVT_MOTION, array(wxID_TOP, "Mouse_Move"));
//
$panel1 = new wxPanel($frame, wxID_ANY, new wxPoint(100, 100), new wxSize(100, 100));
$panel1->SetBackgroundColour(wxBLUE);
$panel1->Connect(wxEVT_MOTION, array(wxID_TOP, "Mouse_Move"));
//
$panel2 = new wxPanel($frame, wxID_ANY, new wxPoint(300, 100), new wxSize(100, 100));
$panel2->SetBackgroundColour(wxBLUE);
$panel2->Connect(wxEVT_MOTION, array(wxID_TOP, "Mouse_Move"));
//
$panel3 = new wxPanel($frame, wxID_ANY, new wxPoint(500, 100), new wxSize(100, 100));
$panel3->SetBackgroundColour(wxBLUE);
$panel3->Connect(wxEVT_MOTION, array(wxID_TOP, "Mouse_Move"));
//
$frame->Show();
wxEntry();
//====================================
function Mouse_Move($event)
{   global $frame, $panel1, $panel2, $panel3 ;
    if($event->Dragging())  
    {   if($panel1->GetScreenRect()->Contains(wxGetMousePosition())) 
        { $panel1->SetBackgroundColour(wxRED); }
        if($panel2->GetScreenRect()->Contains(wxGetMousePosition())) 
        { $panel2->SetBackgroundColour(wxRED); }
        if($panel3->GetScreenRect()->Contains(wxGetMousePosition())) 
        { $panel3->SetBackgroundColour(wxRED); }
        // $frame->Refresh();
    } 
}
?>
```

**Comment by jgmdev** [comment]
My wild guess would be that it is how the underlying toolkit works behind the scenes. On linux that toolkit can be gtk2 or gtk3 while on windows it is the winapi. Also I have noticed that sometimes not initializing using a wxApp can cause issues under windows. But this is surely good information to know for those that may be struggling with this issue.

**Comment by halfer** [comment]
If anyone knows any Python or C, they could try replicating the above script with the respective wxWidgets library. That would indicate whether the issue is GNU/Linux or wxPHP.

(My Python knowledge is largely non-existent, but I do mean to pick some up to get an App Indicator working on Ubuntu and communicating with a wxPHP application).

**Comment by jgmdev** [comment]
wxFormBuilder also generates source code for Python, Lua, etc... so it should be easier to test in those other bindings.

**Comment by davekimble2** [comment]
I did find some old reports of something like this that was accepted for further investigation but you would imagine it had been fixed by now.  The changes cause areas being flagged for re-rendering and put on the event queue, but if nothing further happens to trigger event queue processing, the changes are not made visible.  If the app's window is covered by another window and then uncovered again, the changes are rendered OK. Refresh() and Update() are intended to force this sooner.

In my real app, another action causes the panel colours to be reset, and there either Refresh or Update or both doesn't seem to fix the problem on Windows.  

The eventual target machine will have armhf architecture and most likely Android OS.  My armhf hardware (Cortex v6) is so slow that I am reluctant to put wxPHP onto it, breaking so much new ground (for me).

**Comment by jgmdev** [comment]
> Any chance of an Android build?

There was some work on running wxWidgets in top of QT (which supports android) but functionality is limited and all the features we need to run wxPHP aren't present. To work we would need to implement conditional compiling on wxPHP source to turn off certain fetures for certain targets. I hope in a future to get conditional compiling working with new [code generator](https://github.com/peg-org).
