### ISSUE TITLE
Unmet dependency?

### ISSUE THREAD

**Issue by bitflop** [wxphp/wxphp#119]
Hi

The package (64 bit) for Ubuntu (Debian) doesn't work. Dependency are not met. It is complaining about some "phpapi-20121212" package.

**Comment by halfer** [comment]
@bitflop: I compiled the module under Ubuntu 14.04 a couple of weeks ago. Would you be more specific as to what you did that did not work?

**Comment by bitflop** [comment]
During installation dpkg cannot proceed as the package you have compiled has unmet dependencies ia. package "phpapi-20121212".

```
dpkg -i php5-wxwidgets_3.0.2.0_amd64.deb 
Selecting previously unselected package php5-wxwidgets.
(Reading database ... 304346 files and directories currently installed.)
Preparing to unpack .../php5-wxwidgets_3.0.2.0_amd64.deb ...
Unpacking php5-wxwidgets (3.0.2.0) ...
dpkg: dependency problems prevent configuration of php5-wxwidgets:
 php5-wxwidgets depends on phpapi-20121212; however:
  Package phpapi-20121212 is not installed.

dpkg: error processing package php5-wxwidgets (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 php5-wxwidgets
```

I don't know what "phpapi-20121212" is and apt cannot find the package by itself (which it normally can when issuing apt-get -f install).

**Comment by halfer** [comment]
Hmm, `20121212` isn't a package afaik - it's the version number of a particular PHP module format, as per `/usr/lib/php5/20121212`. What version of PHP do you have on your system?

My guess would be to install `php5-dev` prior to installing this - perhaps that's a dep that should be in this package but is not included.

**Comment by bitflop** [comment]
I thought the same when I tried the installation yesterday, but I already have php5-dev installed:

```
$ dpkg -l | grep php5-dev
ii  php5-dev                              5.6.14+dfsg-0+deb8u1                 amd64        Files for PHP5 module development
```
I am running with PHP 5.6.14.

**Comment by halfer** [comment]
Did you try the link I added at the end?

**Comment by bitflop** [comment]
The link contents is unrelated and pretty useless :)

https://packages.debian.org/search?keywords=phpapi&searchon=names&suite=all&section=all

http://packages.ubuntu.com/search?keywords=phpapi&searchon=names&suite=all&section=all

The package you have made has a dependency which is unmet and phpapi - whatever that is - cannot be installed on either Debian or Ubuntu using APT. You need to provide that package too then ;)

**Comment by halfer** [comment]
I'll leave this thread, then - I'm quite sure that link _was_ related, and I do think you should try it. Please note I don't _need_ to do anything here - I am a user like you, and not a maintainer. I am just trying to be helpful.

**Comment by jgmdev** [comment]
The issue is that the ubuntu deb package I compiled was build against an older version of PHP, but now that ubuntu is distributing a newer version of PHP on their repos the package doesn't works any longer. So the solution would be to build a new deb package from scratch. @bitflop to create a deb file you can basically follow this https://github.com/wxphp/wxphp/wiki/building-on-linux#creating-a-deb-package. Would be nice if someone took maintenance of building ubuntu packages every time a new PHP version is released or the wxphp project is updated with fixes, etc....

**Comment by bitflop** [comment]
@halfer it's not about trying :) It's not related. The purpose of this issue (for me) was just to be helpful letting someone know that the package for download isn't working.

@jgmdev I know, thanks.

I think the best solution is if someone builds packages for Debian, they will work on Ubuntu too, but not always the other way around.

**Comment by halfer** [comment]
@jgmdev: is it worth amending the download page to note that the DEB file doesn't presently work?

@bitflop: what you perceive as helpful doesn't come across as such, I am afraid. If you are willing [to get in touch privately](https://blog.jondh.me.uk/about/) I am willing to take the time to explain why.

**Comment by bitflop** [comment]
@halfer I am sorry, but I think you misunderstand the situation. I addresses this issue off Github at first, ie. contacted the project, a person then asked if I would be kind to simply raise the issue on Github, which I did. That's all. I am not trying to help solve the problem with the package or anything more, I just wanted to let someone know, nothing more.

If that comes of as not helpful, I understand why you might see it as such, but I think me opening the issue to just let someone know - in that the download package needs to be removed - is important enough to be addressed rather than me being quiet about it.

**Comment by halfer** [comment]
@bitflop, yes I understand that now. It is good that you are happy to indicate that something is not working, I applaud the time you have spent on that. But you also need to understand that communities work on goodwill. I don't mind that your initial report was incomplete, or that when I gave two suggestions you only responded to one of them.

But you clearly assumed I was a maintainer, and explained what I "needed" to do, and you also referred to my kind assistance as "useless". It may be that your first language is not English, in which case you need to be informed that this is not just a little rude.

Anyway, I will let the matter rest. My feedback to you is meant to be helpful, I assure you!

**Comment by bitflop** [comment]
@halfer yes, I am sorry, I misunderstood you for the maintainer :)

The "useless" part was not intended to be rude in any way, which is why I also added the smiling face.

As you know the word "useless" may simple refer to something being "pointless" or "without purpose", which is what I meant as that is what the link was from a technical standpoint. Nothing more.

No rudeness intended in any way!

Kindest regards @halfer

**Comment by halfer** [comment]
Thanks @bitflop.

**Comment by jgmdev** [comment]
Well, I upgraded my ubuntu virtual machines uploaded some fresh ubuntu 14.04 builds, feel free to try them http://sourceforge.net/projects/wxphp/files/wxphp/3.0.2.0/Ubuntu%2014.04/
