### ISSUE TITLE
wxPHP website mixes http/s protocols (affects webview.php demo)

### ISSUE THREAD

**Issue by halfer** [wxphp/wxphp#120]
Low priority issue. Running the web demo on PHP 5.5.9 on Ubuntu 14.04 results in streams of console errors thus:

> Message: console message:  @ 0: Blocked a frame with origin "https://googleads.g.doubleclick.net" from accessing a frame with origin "http://wxphp.org".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.

I don't know if you able to affect this, since your usage of Google Ads is protocol relative (`//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js`). Is there a switch that can be supplied when calling Google, so that it loads from an HTTP address?

I'm a little surprised by this error - I did not know that HTTPS inside HTTP would/should be blocked. I thought it was just the other way around.

For completeness, I should state that I am not particularly wanting to see advertisements in the demo, just trying to reduce the errors.

**Comment by jgmdev** [comment]
I did notice that some people where accessing the site with https:// and my custom CMS was serving cached pages with http:// addresses, I fixed that some time ago and uploaded new CMS code to wxPHP site so it should work properly now.

As for ads, I placed them in order to earn some pennies to pay the domain and maybe help with hosting cost.

**Comment by halfer** [comment]
> As for ads, I placed them in order to earn some pennies to pay the domain and maybe help with hosting cost.

Yes, not complaining about the ads - just thought I would explain my motivation `:-)`.

Thanks for looking at it. I'll have a look once I've worked out how to merge your master into mine!

**Comment by halfer** [comment]
Ah, of course, any changes you might have done for this ticket won't be in the wxPHP repo. Either way, running `webview.php` again results in the same errors.

**Comment by jgmdev** [comment]
Sorry, for a moment I thought you meant https issues on wxphp site which I fixed, but I haven't fixed the google ads issue, it doesn't matter if they aren't displayed on the webview demo, I would say is better this way :)

**Comment by halfer** [comment]
Ah, OK - I wondered if it was worth fixing to reduce the worrying-looking errors. Nevertheless error streams from established apps does seem normal - the wxFormBuilder sends them out at quite a rate!
