### ISSUE TITLE
choicelistbox.php doesn't need to ask whether to open the window

### ISSUE THREAD

**Issue by halfer** [wxphp/wxphp#121]
The `choicelistbox.php` demo script asks the user whether to open a window. Given that the purpose of the demo is to demonstrate the choice list, it seems sensible to remove this, for consistency with other demos, and to get to the point of the example immediately.

Is it OK to raise a PR for this?

**Comment by jgmdev** [comment]
Sure, that was just a quick test for the wxMessageBox if I recall correctly, but as you say, is better to create a separate demo to showcase the wxMessageBox and clean the choicelistbox.php demo.
