### ISSUE TITLE
Add support for IPC subsystem

### ISSUE THREAD

**Issue by halfer** [wxphp/wxphp#128]
wxWidgets seems to have support [for inter-process communication](http://docs.wxwidgets.org/3.0/group__group__class__ipc.html). However, I can't find references to `wxConnection` etc [in the wxPHP docs](http://wxphp.org/reference/index.html), and so assume it is not available for PHP apps. Can it be added? I assumed that the PHP wrapper would contain everything in wxWidgets 3.0?

Note: I don't _need_ this, but would like to write an IPC demo for another pull request.

**Comment by jgmdev** [comment]
If I remember correctly I didn't added it because php has builtin support for sockets as other features that serve for the same purpose.

**Comment by halfer** [comment]
Gotcha, no problem. I quite liked the idea of trying it because it would (presumably) raise WX events when a message is received, and thus would be cleaner than sockets, which still needs threads on the server side. Not a problem though - as we've said elsewhere, the file watcher can do this.
