### ISSUE TITLE
building on armhf - success in the end

### ISSUE THREAD

**Issue by davekimble2** [wxphp/wxphp#134]
I have a new OrangePI PC - a RaspberryPi clone with a quad core H3 processor (arm v7L) running Lubuntu 14.04 .  An amazing piece of kit for $15, but the case doesn't give adequate ventilation, so I'm running it naked and standing on edge - reduces temp from 75 to 60°C.

Following /wxphp/INSTALL.md :
wxWidgets builds OK ('make' takes 82 minutes)
wxPHP 'configure' fails because wxWidgets has no classes wxWebView and wxMediaCtrl, as if those libraries are optional for wxWidgets but not for wxPHP.

I installed the necessary libraries and started again.

wxphp 'make' kept failing "internal compiler error" at different places, which I first thought was due to overheating, but later discovered it was "out of memory" (the OrangePI only has 1GB RAM and the Lubuntu image doesn't have a swap file).  Anyway I finally wrestled it into submission.

And my wxPHP script that displays the temperature sensor readings and other stuff worked nicely first time.  :)

INSTALL.md needs some minor adjustments.

**Comment by jgmdev** [comment]
Good to know you got it working, and yes, building instructions need a refresh even this seems to be outdated https://github.com/wxphp/wxphp/wiki/building-on-linux

For the most part you can run ./configure without any arguments and it will take care of downloading wxWidgets 3.0.2 and compiling it to suit wxPHP (this method does static linkage), it will also warn you about missing dependencies so you don't loose time compiling to discover something went wrong.

Here https://github.com/wxphp/wxphp/blob/master/config.m4#L61 from that point onward you can see all the required dependencies for linux but the configure script will only trigger those error messages if ./configure is ran without parameters.
