### ISSUE TITLE
Incorrect links on download page

### ISSUE THREAD

**Issue by underdpt** [wxphp/wxphp#138]
Hi,

The download page link to latest windows x64 release says:

wxphp-3.0.0.2-php5.5-x64.exe

But points to:
http://sourceforge.net/projects/wxphp/files/wxphp/3.0.2.0/Windows/wxphp-3.0.2.0-php5.6-x64.exe/download

So it should be:
wxphp-3.0.2.0-php5.6-x64.exe

**Comment by jgmdev** [comment]
Fixed, Thanks!
