### ISSUE TITLE
Tried to install php5-wxwidgets_3.0.2.0_amd64.deb on debian/jessie

### ISSUE THREAD

**Issue by eriksank** [wxphp/wxphp#141]
Hi,

I've tried to install `php5-wxwidgets_3.0.2.0_amd64.deb` on the latest (stable) `debian/jessie`.

    $ gdebi php5-wxwidgets_3.0.2.0_amd64.deb
    This package is uninstallable
    Dependency is not satisfiable: libjpeg8 (>= 8c)

In my impression `libjpeg8` was discontinued in Debian after `debian/wheezy`:

https://packages.debian.org/sid/libjpeg8 

`debian/jessie` comes with `libjpeg62-turbo`. I have no idea as to what Debian's policy decisions were, to do it that way. The result is that the pre-packaged download no longer installs on Debian. How can we get the download to work properly again on Debian?

**Comment by jgmdev** [comment]
Well, besides modifying the build files to try and link against libjpeg62 and recompiling from source. Another alternative would be to extract the contents of the deb file, inspect the wxwidgets.so linked libraries with **ldd wxwidgets.so** and maybe if the symbols from libjpeg62 and libjpeg8 are the same, create a link file with the same name used for libjpeg8 to libjpeg62 in the /usr/lib directory (if that is the correct one for this library). But, I'm not sure that would work, this is me just supposing :thought_balloon:

**Comment by eriksank** [comment]
dpkg -i php5-wxwidgets_3.2.0.2.0_amd64.deb 
    Selecting previously unselected package php5-wxwidgets.
    (Reading database ... 161270 files and directories currently installed.)
    Preparing to unpack php5-wxwidgets_3.2.0.2.0_amd64.deb ...
    Unpacking php5-wxwidgets (3.0.2.0) ...
    dpkg: dependency problems prevent configuration of php5-wxwidgets:
     php5-wxwidgets depends on libjpeg8 (>= 8c); however:
      Package libjpeg8 is not installed.
     php5-wxwidgets depends on phpapi-20121212; however:
      Package phpapi-20121212 is not installed.

It is the debian control file that insists on the package being present and it won't deploy the files if there are missing packages. In fact, even solving that problem, it would leave another one there: Wrong PHP API. It is almost impossible to distribute a PHP extension as a binary, because it insists on the right API version being installed on the machine. I guess it would probably be simpler to distribute the extension inclusive of PHP itself, or to just recompile from scratch ...

**Comment by jgmdev** [comment]
You can try running the [appimage](http://wxphp.org/news/wxphp-appimage) to see if it works for you under debian (I tested on ubuntu 14.04/16.04).
