### ISSUE TITLE
Build for php 7.0 version

### ISSUE THREAD

**Issue by ganeshkbhat** [wxphp/wxphp#148]
Is there a build available for php 7.0 version?

**Comment by halfer** [comment]
There is a branch for it, but I don't know what state it is in.

**Comment by jgmdev** [comment]
Haven't found time to port to PHP 7, but it is on the pipeline of things to do. If running on linux in a distro that dropped php 5 then you can try the [appimages](http://wxphp.org/news/wxphp-appimage)
