### ISSUE TITLE
Ubuntu 16.04 drops php5 support

### ISSUE THREAD

**Issue by davekimble2** [wxphp/wxphp#150]
Lubuntu 16.04 (64), PHP 7.0 installed

Tried installing php5-wxwidgets_3.0.2.0_amd64.deb
**dpkg -i **gives 
"Error: Dependency is not satisfiable: phpapi-20121212"

**apt-get install -f** gives 
"unmet dependencies:
php5-wxwidgets depends phpapi-20121212
php5-wxwidgets depends php5-cli"

and they (php5-common holds phpapi-20121212) have apparently been dropped from the 16.04 repository.

I've still got /var/cache/apt/archives/php5_5.5.9+dfsg-1ubuntu4.16_amd64.deb and other php5*.deb files on another PC.
Can I send this across to the 16.04 machine and install it there?
It installs in /usr/lib/php5 whereas in 16.04 PHP7 lives in /usr/lib/php/PHP-7.0 so they don't appear to clash, but I don't want to mess up my new clean OS.

**Comment by davekimble2** [comment]
In answer to the above - no.
In 14.04 PHP should install into /usr/lib/php5/ , but in 16.04 it goes in /usr/lib/php/5.5/ , so the .deb files are going to do the wrong things if copied from 14.04 to 16.04 and used.

There is a group of repositories called ppa:ondrej/php* which claims to solve all the problems of the lack of PHP5 support on Ubuntu 16.04 (and lack of PHP7 on Ubuntu 14.04).

Unfortunately some of the descriptions of how to use them are wrong, and I think even the author's descriptions at https://launchpad.net/~ondrej are confusing.  However ondrej@sury.org quickly set me right and I successfully installed php5.5-cli on 16.04.

I then tried installing php5-wxwidgets_3.0.2.0_amd64.deb again, but no luck -
now there is a naming problem: the package is looking for dependency php5-cli, and the software is present but called php5.5-cli.

It occurs to me that if the wxPHP package was built including the PHP modules it is designed for, (not linked to), then all of these dependency problem would disappear, although the package would be bigger.  If the file was named for example **wxphp_3.0.2.0_php_5.5.9_wxwidgets_3.0.2_amd64.deb**
then it would be clear what you are getting.

**Comment by jgmdev** [comment]
Sorry that I have been so disconnected with the project, recently I was playing with AppImageKit project which is a way of distributing software for linux that doesn't depends on specific distro packaging stuff. I was able to package wxPHP with PHP 5.6.23 and wrote a post about it with download links http://wxphp.org/news/wxphp-appimage you can try that to see if it works for you, the gtk2 version should work properly on Ubuntu 16.04 since I tested it on a fresh Ubuntu install.

**Comment by davekimble2** [comment]
http://wxphp.org/news/wxphp-appimage is blocking my IP as spam.

**Comment by jgmdev** [comment]
Since I was getting a lot of spam on forums I started using a database from stopforumspam that has all spam ip's used over the year I changed this to use a less extensive database. Please try now and let me know.

**Comment by davekimble2** [comment]
OK.
wxphp-gtk2 now working on 16.04
Thank you very much for that.

**Comment by chennaiiq** [comment]
I am a php developer, new to ubuntu/linux. I try to use wxphp - appimage by downloading from [here](https://github.com/wxphp/appimage) and run ./appimage.

I got lot of errors like following which I solved by googling

xml2-config not found. Please check your libxml2 installation
configure: error: Cannot find OpenSSL's <evp.h>
configure: error: png.h not found.
configure: error: mcrypt.h not found. Please reinstall libmcrypt.
...
...

finally I got error "configure: error: webkitgtk include files where not found"

Is it right way I am doing?. Please help me to install wxPhp in my Ubuntu 16.04 64bit.

Please explain/guide me step by step.

**Comment by jgmdev** [comment]
@chennaiiq thats to build an appimage, if you only want to get a working appimage you can download the latest versions from https://sourceforge.net/projects/wxphp/files/wxphp/3.0.2.0/AppImage
