### ISSUE TITLE
Problem with reference counted objects

### ISSUE THREAD

**Issue by tsahlin** [wxphp/wxphp#17]
There is a problem with functions that return reference counted objects such as wxFont.

For example using the method GetFont in wxWindow:

```php
$font = $this->GetFont();
var_dump($font->GetFaceName());
```

This will often lead to a seg fault because the underlying wxFont has been freed when $font->GetFaceName is called.

I've tried fixing PHP_METHOD(php_wxWindow, GetFont), and increasing the reference count of the returned value helps the problem:

```cpp
wxFont value_to_return0;
value_to_return0 = ((wxWindow_php*)native_object)->GetFont();

((wxRefCounter *) value_to_return0.GetRefData())->IncRef();

void* ptr = safe_emalloc(1, sizeof(wxFont_php), 0);
memcpy(ptr, &value_to_return0, sizeof(wxFont));
object_init_ex(return_value, php_wxFont_entry);
```

I haven't yet looked into how to solve it in the code generator. Perhaps you have an idea of how to do it?

**Comment by jgmdev** [comment]
I let this issue open as a reminder of the issue but so far all issues that caused crashes on wxPHP due to issue described above seem to be fixed so I'm closing for now.
