### ISSUE TITLE
wxTextCtrl SetMargins

### ISSUE THREAD

**Issue by davekimble2** [wxphp/wxphp#71]
Lubuntu 14.04, php 5.5.9, wxphp 3.0.0.1, wxWidgets 3.0.0.1

```
<?php
$window = new wxFrame(null, wxID_TOP, "test", wxDefaultPosition, new wxSize(640, 480) );
$vbox = new wxBoxSizer(wxVERTICAL);
$textbox = new wxTextCtrl( $window, wxID_ANY, "", wxDefaultPosition, new wxSize( 620, 460), wxTE_MULTILINE );
$textbox->SetMargins(5, 5);
$vbox->Add($textbox, 0, wxALL, 10);
$window->SetSizer($vbox);
$window->Show();
wxEntry();
?>
```
Terminal output:
(php:18854): GLib-GObject-WARNING **: invalid cast from 'GtkTextView' to 'GtkEntry'

(php:18854): Gtk-CRITICAL **: IA__gtk_entry_get_inner_border: assertion 'GTK_IS_ENTRY (entry)' failed

(php:18854): Gtk-CRITICAL **: IA__gtk_entry_set_inner_border: assertion 'GTK_IS_ENTRY (entry)' failed

Removing the SetMargins() fixes this. Why?
Either way, when typing into the box, once an upper case letter has been typed, typing {ENTER} doesn't show up in the control until you switch  to another app and switch back. Very odd behaviour.

**Comment by jgmdev** [comment]
I added a pair of 2 new constants that correctly reflect the wxPHP version and wxWidgets version that can be seen here https://github.com/wxphp/wxphp/blob/master/tools/source_maker/source_templates/wxwidgets.cpp#L318

Basically these are: 
* WXWIDGETS_EXTENSION_VERSION
* WXWIDGETS_LIBRARY_VERSION
