### ISSUE TITLE
versions info incorrect ?

### ISSUE THREAD

**Issue by davekimble2** [wxphp/wxphp#72]
I tweaked the script to display version numbers a bit, to make it run on Windows as well.
I have Lubuntu (x86) > VirtualBox > Win-XP and Win-7.
Neither had wxphp on them, so I was starting from a clean state.
http://wxphp.org/download#windows says wxphp 3.0.0.2 is built against wxWidgets 3.0.1,
which doesn't sound right, but following that anyway, I downloaded and installed:
vcredist_x86.exe
wxMSW-3.0.1-vc90-x86-ReleaseDLL.msi
wxphp-3.0.0.2-php5.4-x86.exe

Set PATH = C:\Program Files\wxPHP\php , reboot
Edited php.ini for date.timezone
On Win-7 this wouldn't save because of access denied to \Program Files\ not running as Admin.

Ran the app from the commandline
Moments after the windows appears, wxphp.exe crashes in php5ts.dll , and VirtualBox sometimes crashes in sympathy.
This happens on both XP and 7.
By commenting out various bits, it appears to be nothing to do with the script.

So is http://wxphp.org/download#windows wrong ?
Unstalled wxWidgets_3.0.1 and installed wxWidgets_3.0.0, but the same thing happens.

Trying it on Raspian Wheezy :
php5-wxwidgets_3.0.0.2_armhf.deb gives a cascade of unmet dependencies on install.
There must be some virtual package that brings that lot in, but what?

```
<?php
$window = new wxFrame(null, wxID_TOP, "Versions");
$vbox = new wxBoxSizer(wxVERTICAL);
$textbox = new wxTextCtrl( $window, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE );
//$textbox->SetMargins(new wxPoint(5, 5));
$textbox->SetValue(getversions());
$vbox->Add($textbox, 1, wxEXPAND|wxALL, 10);
$window->SetSizer($vbox);
$window->Show();
wxEntry();
//
function getversions()
{	$php = "PHP ".phpversion().PHP_EOL;
	// get phpinfo() as string
	$script = "<?php phpinfo(INFO_MODULES); ?>";
	file_put_contents("phpinfo.php", $script);
	exec("wxphp phpinfo.php > phpinfo.txt");
	$phpinfo= file_get_contents("phpinfo.txt");
	// get wxPHP extension value
	$p1 = strpos($phpinfo, "wxWidgets");
	if(!$p1)
	{	$wxphp = "wxPHP not found".PHP_EOL ;
		$wxwidgets = "wxWidgets not found".PHP_EOL ;
		goto close:
	}
	$p1 = strpos($phpinfo, "Extension Version => ", $p1)+21;
	$p2 = strpos($phpinfo, PHP_EOL, $p1);
	$wxphp = "wxPHP ".substr($phpinfo, $p1, ($p2 - $p1)).PHP_EOL;
	// get wxWidgets value
	$p3 = strpos($phpinfo, "wxWidgets Version => ", $p2)+21;
	$p4 = strpos($phpinfo, PHP_EOL, $p3);
	$wxwidgets = "wxWidgets ".substr($phpinfo, $p3, ($p4 - $p3)).PHP_EOL ;
	//
	close:
	unlink("phpinfo.php");
	unlink("phpinfo.txt");
	return $php.$wxphp.$wxwidgets ;
}
?>
```

**Comment by jgmdev** [comment]
I just added the following 2 constants to retrieve version info: WXWIDGETS_LIBRARY_VERSION (wxWidgets version aka main library) and WXWIDGETS_EXTENSION_VERSION (wxPHP version aka wrapper). Closing this now.
