### ISSUE TITLE
wxFormBuilder & wxPHP

### ISSUE THREAD

**Issue by NetWielder** [wxphp/wxphp#77]
The wxPHP tutorial recommends I use wxFormBuilder to create the user interface however the latest version of wxFormBuilder doesn't have the PHP code generation feature enabled or perhaps it doesn't exists.

How did this tutorial utilize PHP code generation? Is there someway I can enable this feature?

http://wiki.wxphp.org/Introduction_to_using_wxPHP_Example#Class_Properties_not_direct_PHP_Variables

Any feedback is greatly appreciated!
Mike :-)

**Comment by chrisnharvey** [comment]
I believe the PHP code generation is part of the latest nightly builds of wxFormBuilder.

http://sourceforge.net/projects/wxformbuilder/files/wxformbuilder-nightly/3.5.0-beta/

**Comment by NetWielder** [comment]
After building from source, PHP code generators are visible in the user interface. Thanks :-)

**Comment by halfer** [comment]
@NetWielder: you can also use the [XPC system](https://github.com/wxphp/wxphp/tree/master/examples/XRC). I just recently added a demo, and another update hopefully will be merged down soon. This is in the version of wxFormBuilder in the Ubuntu repo (3.1.59-beta).
