### ISSUE TITLE
Media playback error: Internal data stream error.

### ISSUE THREAD

**Issue by torstahl** [wxphp/wxphp#85]
Hello
when i trie to play a ogg musk file with the wxMediactrl on Linux (OpeneSUSE 13.1) i got this error.
09:04:39: Media playback error: You do not have a decoder installed to handle this file. You might need to install the necessary plugins. 
with gst-launch-0.10 playbin uri=file:///home/torsten/Videos/lied.ogg on the console i can play this file.

here the console output
** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

(php:3500): GStreamer-CRITICAL **: gst_buffer_map_range: assertion 'GST_IS_BUFFER (buffer)' failed

** (php:3500): CRITICAL **: file gstvorbistag.c: line 519 (gst_tag_list_from_vorbiscomment_buffer): should not be reached

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

(php:3500): GLib-GObject-WARNING **: specified class size for type 'GstVorbisEnc' is smaller than the parent type's 'GstAudioEncoder' class size

(php:3500): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(php:3500): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(php:3500): GStreamer-CRITICAL **: gst_element_register: assertion 'g_type_is_a (type, GST_TYPE_ELEMENT)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed
** Message: don't know how to handle audio/x-vorbis, rate=(int)44100, channels=(int)2

** (php:3500): CRITICAL **: gst_missing_decoder_message_new: assertion 'GST_IS_CAPS (decode_caps)' failed

(php:3500): GStreamer-CRITICAL **: gst_element_post_message: assertion 'message != NULL' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

(php:3500): GStreamer-CRITICAL **: gst_buffer_map_range: assertion 'GST_IS_BUFFER (buffer)' failed

** (php:3500): CRITICAL **: file gstvorbistag.c: line 519 (gst_tag_list_from_vorbiscomment_buffer): should not be reached

** (php:3500): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

an may php code:
        $this->med = new wxMediaCtrl();
        $this->med->Connect(wxEVT_MEDIA_STOP,[$this,'VideoOnStop']);
        $this->med->Connect(wxEVT_MEDIA_PAUSE,[$this,'VideoOnPause']);
        $this->med->Connect(wxEVT_MEDIA_PLAY,array($this,'VideoOnPlay'));
        $this->med->Connect(wxEVT_MEDIA_FINISHED,[$this,'VideoOnFinished']);
        $this->med->Connect(wxEVT_MEDIA_LOADED,[$this,'VideoOnLoaded']);

        $this->med->Create($this,wxID_ANY,wxEmptyString,wxDefaultPosition,new wxSize(640,480));
        $this->med->Load('/home/torsten/Videos/lied.ogg');
        $this->med->ShowPlayerControls();

        function VideoOnLoaded()
        {
                echo "Video Loaded\n";
                $this->med->Play();
        }

Best Regards
Torsten

**Comment by jgmdev** [comment]
Close this since issue #86 should cover further discussion.
