### ISSUE TITLE
wxMediaCtrl gstreamer play not all formats

### ISSUE THREAD

**Issue by torstahl** [wxphp/wxphp#86]
Hello 

i tried to play some Videos 
- dothack2.mpg: MPEG sequence, v2, program multiplex
- Futurama1-tmp.avi: RIFF (little-endian) data, AVI, 480 x 480, 23.98 fps, video:, audio: Dolby AC3 (stereo,  48000 Hz)
- lied.ogg: Ogg data, Vorbis audio, stereo, 44100 Hz, ~128003 bps, created by: Xiph.Org libVorbis I (pre-1.0 CVS)
- small.flv: Macromedia Flash Video
- small.mp4: ISO Media, MPEG v4 system, version 2
- small.ogv: Ogg data, Skeleton v3.0
- small.webm: WebM
- toddle.mp3: Audio file with ID3 version 2.3.0, contains: MPEG ADTS, layer III, v2,  64 kbps, 22.05 kHz, JntStereo

i can play all this files from console with gst-launch-0.10 playbin uri=file://

same code as i report #85 

I can only play ogv and webm videos with wxMediactrl but without sound, same error as in issue #85 

with mp3 i got no Xwindow only:
** (php:5957): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:5957): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:5957): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:5957): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:5957): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:5957): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:5957): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:5957): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:5957): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

(php:5957): GLib-GObject-WARNING **: cannot register existing type 'GstValueList'

(php:5957): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(php:5957): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(php:5957): GLib-CRITICAL **: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

with avi file i got a Xwindow with message
Media playback error: Das Element »volume« fehlt - überprüfen Sie Ihre Installation von GStreamer.
** (php:5991): CRITICAL **: gst_audio_buffer_clip: assertion 'segment->format == GST_FORMAT_TIME || segment->format == GST_FORMAT_DEFAULT' failed

** (php:5991): CRITICAL **: gst_audio_buffer_clip: assertion 'segment->format == GST_FORMAT_TIME || segment->format == GST_FORMAT_DEFAULT' failed

** (php:5991): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

with mpeg 2 videos i got a Xwindow but the video frame still is black with console output
** (php:6018): CRITICAL **: gst_audio_buffer_clip: assertion 'segment->format == GST_FORMAT_TIME || segment->format == GST_FORMAT_DEFAULT' failed

** (php:6018): CRITICAL **: gst_audio_buffer_clip: assertion 'segment->format == GST_FORMAT_TIME || segment->format == GST_FORMAT_DEFAULT' failed

** (php:6018): CRITICAL **: gst_audio_buffer_clip: assertion 'segment->format == GST_FORMAT_TIME || segment->format == GST_FORMAT_DEFAULT' failed

** (php:6018): CRITICAL **: gst_audio_buffer_clip: assertion 'segment->format == GST_FORMAT_TIME || segment->format == GST_FORMAT_DEFAULT' failed

** (php:6018): CRITICAL **: gst_is_missing_plugin_message: assertion 'GST_IS_MESSAGE (msg)' failed

** (php:6018): CRITICAL **: gst_audio_buffer_clip: assertion 'segment->format == GST_FORMAT_TIME || segment->format == GST_FORMAT_DEFAULT' failed

** (php:6018): CRITICAL **: gst_audio_buffer_clip: assertion 'segment->format == GST_FORMAT_TIME || segment->format == GST_FORMAT_DEFAULT' failed

** (php:6018): CRITICAL **: gst_audio_buffer_clip: assertion 'segment->format == GST_FORMAT_TIME || segment->format == GST_FORMAT_DEFAULT' failed

Best Regards
Torsten

**Comment by jgmdev** [comment]
I haven't been able to get wxMediaCtrl playing anything under linux. It is really interesting that you were able to get it playing some file formats, did you do anything special? Sample code?

On issue #27 I added some note on how to debug the issue, but I haven't done it. Some help on this would be nice.

**Comment by torstahl** [comment]
Hello

![wxphp3](https://cloud.githubusercontent.com/assets/7045190/6282629/5a34ad42-b8d8-11e4-8d7b-df7aa2cc2c04.png)

class MyFrame1 extends wxFrame {
    function __construct( $parent=null ){
        parent::__construct ( $parent, wxID_ANY, wxEmptyString, wxDefaultPosition, new wxSize( 500,300 ), wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL );

        $this->SetSizeHints( wxDefaultSize, wxDefaultSize );

        $bSizer1 = new wxBoxSizer( wxVERTICAL );

        $this->med = new wxMediaCtrl();
        $this->med->Connect(wxEVT_MEDIA_STOP,[$this,'VideoOnStop']);
        $this->med->Connect(wxEVT_MEDIA_PAUSE,[$this,'VideoOnPause']);
        $this->med->Connect(wxEVT_MEDIA_PLAY,array($this,'VideoOnPlay'));
        $this->med->Connect(wxEVT_MEDIA_FINISHED,[$this,'VideoOnFinished']);
        $this->med->Connect(wxEVT_MEDIA_LOADED,[$this,'VideoOnLoaded']);

        $this->med->Create($this,wxID_ANY,wxEmptyString,wxDefaultPosition,new wxSize(640,480));
        $this->med->Load('/home/torsten/Videos/Wildlife.ogv');
        $this->med->ShowPlayerControls();

        $bSizer1->Add( $this->med, 0, wxALL, 5 );
        $this->SetSizer( $bSizer1 );
        $this->Layout();

        $this->Centre( wxBOTH );
    }
    function __destruct( ){
    }
    function VideoOnLoaded()
    {
          echo "Video Loaded\n";
          $this->med->Play();
     }
    function VideoOnFinished()
    {
            echo "Video Finished\n";
    }
    function VideoOnPause()
    {
            echo "Video Pause\n";
    }
    function VideoOnStop()
     {
           echo "Video Stop\n";
     }
     function VideoOnPlay()
     {
            echo "Video Play\n";
     }
}

//Application initialization start point
class myApp extends wxApp
{
    function OnInit()
    {
        $zs = new MyFrame1();
        $zs->Show();
        $this->frm = $zs;
        return true;
    }

    function OnExit()
    {
        return 0;
    }
}

wxInitAllImageHandlers();
$gridApp = new myApp();
wxApp::SetInstance($gridApp);
wxEntry();

**Comment by torstahl** [comment]
so the prolbem ist the mediactrl.cpp file there comes also the error from Dave #27 
the command's to find the videosink or audiosink make some mistakes.
The gst-launch works well on the console so the problems is not the gstreamer it must the mediactrl.cpp

to make a workaround i try to embed the mplayer as i have seen in some c++ or wxpython examples.
mplayer has the option -wid 
-wid <Window-ID> (only with X11, OpenGL und DirectX)
so it should work like this
http://www.blog.pythonlibrary.org/2010/07/24/wxpython-creating-a-simple-media-player/ or 
https://forums.wxwidgets.org/viewtopic.php?f=1&t=14458

the mplayer should connect to the window
    function __construct( $parent=null ){
        parent::__construct ( $parent, wxID_ANY, wxEmptyString, wxDefaultPosition, new wxSize( 500,300 ), wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL );

        $this->SetSizeHints( wxDefaultSize, wxDefaultSize );
        $bSizer1 = new wxBoxSizer( wxVERTICAL );
       // create a panel
        $panel = new wxPanel ( $this, wxID_ANY, wxDefaultPosition, new wxSize( 480,280 ),wxTAB_TRAVERSAL,"PANEL");
        $bSizer1->Add($panel,1,wxEXPAND | wxALL,5);
   
         // get the panel id 
        $x = $panel->GetID();

        // set the panel id 
        $this->med = wxProcess::Open("mplayer -nofs -noquiet -identify -nomouseinput -sub-fuzziness 1 -slave -input file=/tmp/mpl -wid $x /home/torsten/Videos/Futurama1-tmp.avi");
        $this->med->Redirect();

        $this->SetSizer( $bSizer1 );
        $this->Layout();

        $this->Centre( wxBOTH );
    }

but mplayer is opened in a new window
tried under Windows 8 and OpenSUSE 13.1

**Comment by torstahl** [comment]
i see my fault with the mplayer wxWidgets had to build with configure --with-x11 --with-universal 
i give it a try

**Comment by torstahl** [comment]
so i try to build the wxWidgets --with-X11 in place of --with-gtk3 
wxWidgets build without error but not the wxphp

In file included from /home/torsten/build/wxphp/src/appmanagement.cpp:17:0:
/home/torsten/build/wxphp/includes/cmndlg.h: In constructor 'wxFileDialog_php::wxFileDialog_php(wxWindow*, const wxString&, const wxString&, const wxString&, const wxString&, long int, const wxPoint&, const wxSize&, const wxString&)':
/home/torsten/build/wxphp/includes/cmndlg.h:488:462: error: no matching function for call to 'wxFileDialog::wxFileDialog(wxWindow*&, const wxString&, const wxString&, const wxString&, const wxString&, long int&, const wxPoint&, const wxSize&, const wxString&)'
  wxFileDialog_php(wxWindow* parent, const wxString& message=wxFileSelectorPromptStr, const wxString& defaultDir=wxEmptyString, const wxString& defaultFile=wxEmptyString, const wxString& wildcard=wxFileSelectorDefaultWildcardStr, long style=wxFD_DEFAULT_STYLE, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, const wxString& name=wxFileDialogNameStr):wxFileDialog(parent, message, defaultDir, defaultFile, wildcard, style, pos, size, name){}
                                                       
                                                                                                                                                                                                                                                               ^
/home/torsten/build/wxphp/includes/cmndlg.h:488:462: note: candidates are:
In file included from /home/torsten/build/wxphp/wxWidgets-build/include/wx-3.0/wx/filedlg.h:229:0,
                 from /home/torsten/build/wxphp/wxWidgets-build/include/wx-3.0/wx/wx.h:93,
                 from /home/torsten/build/wxphp/includes/common.h:35,
                 from ./php_wxwidgets.h:19,
                 from /home/torsten/build/wxphp/src/appmanagement.cpp:12:
/home/torsten/build/wxphp/wxWidgets-build/include/wx-3.0/wx/generic/filedlgg.h:139:5: note: wxFileDialog::wxFileDialog(wxWindow*, const wxString&, const wxString&, const wxString&, const wxString&, long int, const wxPoint&, const wxSize&)
     wxFileDialog(wxWindow *parent,
     ^
/home/torsten/build/wxphp/wxWidgets-build/include/wx-3.0/wx/generic/filedlgg.h:139:5: note:   candidate expects 8 arguments, 9 provided
/home/torsten/build/wxphp/wxWidgets-build/include/wx-3.0/wx/generic/filedlgg.h:137:5: note: wxFileDialog::wxFileDialog()
     wxFileDialog() {}
     ^
/home/torsten/build/wxphp/wxWidgets-build/include/wx-3.0/wx/generic/filedlgg.h:137:5: note:   candidate expects 0 arguments, 9 provided
/home/torsten/build/wxphp/wxWidgets-build/include/wx-3.0/wx/generic/filedlgg.h:134:24: note: wxFileDialog::wxFileDialog(const wxFileDialog&)
 class WXDLLIMPEXP_CORE wxFileDialog: public wxGenericFileDialog
                        ^
/home/torsten/build/wxphp/wxWidgets-build/include/wx-3.0/wx/generic/filedlgg.h:134:24: note:   candidate expects 1 argument, 9 provided
In file included from /home/torsten/build/wxphp/src/appmanagement.cpp:19:0:
/home/torsten/build/wxphp/includes/ctrl.h: At global scope:
/home/torsten/build/wxphp/includes/ctrl.h:3793:60: error: expected class-name before '{' token
 class wxBitmapToggleButton_php: public wxBitmapToggleButton{


an so on.
is it possible to build wxphp with wxWidgets build with X11  and not gtk ?

**Comment by jgmdev** [comment]
This is what I replied on the wxPHP mailing:

> GetHandle() should return a pointer to the native widget,  while GetId() will return the internal numeration (ID) of the widget as assigned by wxWidgets.

> What exactly requires -wid ? The address of the memory space that holds the window? If thats the case then GetHandle() needs to be implemented.

> Please open a issue on github for implementing wxWindow::GetHandle() on github if needed.

wxX11 isnt supported since as far as I know that port lacks a lot of features and it isnt as maintained as the wxGtk port. Going back to GetHandle(), maybe implementing that would work since GetID is a wxWidgets thing, while GetHandle should return a pointer to the native widget/window, since the wxPHP binding is not going to support resources to native objects, instead GetHandle would return a integer value representing the memory portion the pointer is pointint too.

In any case I will reference this issue when I'm able to implement wxWindow::GetHandle

**Comment by jgmdev** [comment]
The following code should work: 

```php
<?php

class Player extends wxFrame
{

    function __construct( $parent=null ){
		parent::__construct ( 
            $parent, 
            wxID_ANY, 
            wxEmptyString, 
            wxDefaultPosition, 
            new wxSize( 500,300 ), 
            wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL 
        );
		
		$this->SetSizeHints( wxDefaultSize, wxDefaultSize );
		
		$bSizer1 = new wxBoxSizer( wxVERTICAL );
		
		$this->m_panel1 = new wxPanel( 
            $this, 
            wxID_ANY, 
            wxDefaultPosition, 
            wxDefaultSize, 
            wxTAB_TRAVERSAL 
        );
        
		$bSizer1->Add( $this->m_panel1, 1, wxEXPAND | wxALL, 5 );
		
		$this->SetSizer( $bSizer1 );
		$this->Layout();
		
		$this->Centre( wxBOTH );
        
        // Add timer to embed mplayer right after initialization
        $this->m_timer1 = new wxTimer();
        $this->m_timer1->SetOwner( $this, wxID_ANY );
		$this->Connect( wxID_ANY, wxEVT_TIMER, array($this, "Test") );
        
        $this->Show();
        
        // To properly get the m_panel1 handle we need to first
        // fully initialize the window.
        $this->m_timer1->Start( 200 );
	}
    
	function Test( $event ){
        $x = $this->m_panel1->GetHandle();
        
		// set the panel id 
        $this->med = wxProcess::Open("mplayer -nofs -noquiet -identify -sub-fuzziness 1 -slave -input file=/tmp/mpl -wid $x /home/torsten/Videos/Futurama1-tmp.avi");
        $this->med->Redirect();
        
        $this->m_timer1->Stop();
	}

}

$frame = new Player();

wxEntry();
```

**Comment by torstahl** [comment]
Works PERFECT!!!
Thank you very much!!

![wxplay](https://cloud.githubusercontent.com/assets/7045190/6313989/c74999fc-b9c7-11e4-8065-ac3b307b5386.png)

**Comment by jgmdev** [comment]
Great! If you are able to develop a custom wxMediaPlayer component, would be nice if you can share it.
