### ISSUE TITLE
wxOutputStream::Write & wxInputStream::Read

### ISSUE THREAD

**Issue by torstahl** [wxphp/wxphp#87]
Hello 

there is only a stream argument available for input.
wxOutputStream& Write ( wxInputStream &$stream_in )

in the wxWidgets documentation there are more options as argument
http://docs.wxwidgets.org/trunk/classwx_output_stream.html
Write (const void *buffer, size_t size)
Write (wxInputStream &stream_in)

i want to control the mplayer in slave mode
        $this->med = wxProcess::Open("mplayer -idle -slave -quiet -wid $x");
        $this->med->Redirect();

        $m_in = $this->med->GetInputStream();
        $m_out = $this->med->GetOutputStream();

But i can not write a string to the OutputStream 
so i'd like to send  $m_out->Write('loadfile myvideo.mpg');
and also the 
wxInputStream::Read takes only a stream as argument so it is not possile to read from the stream.

Read (void *buffer, size_t size)
Read (wxOutputStream &stream_out)

OT: how can I embed the mplayer to my windows ?

Best Regards
Torsten

**Comment by jgmdev** [comment]
The generator was skipping this overrides of Read and Write because on the past an issue with virtual methods overriding non virtual methods was producing (still producing) compilation errors.

I have enabled the Read and Write variations but didn't test if it is working properly.

> OT: how can I embed the mplayer to my windows ?

Never done that my self.

**Comment by torstahl** [comment]
i build it new
the Read seems to work i get a output back from the stream

        $this->med = wxProcess::Open("mplayer -slave -idle -nolirc -quiet /home/torsten/Videos/small.ogv");
        $this->med->Redirect();

        $this->m_in = $this->med->GetInputStream();
        $this->m_out = $this->med->GetOutputStream();

        $out = '';
        $this->m_in->Read($out, 1024);
        echo "OUT: $out";

      OUT: MPlayer -4.7 (C) 2000-2014 MPlayer Team

and also the Write works! 
        $cmd = "loadfile /home/torsten/Videos/small.ogv\n";
        $this->m_out->Write($cmd, strlen($cmd));
importend is the linefeed

Works perfect!!!

**Comment by jgmdev** [comment]
Thanks for testing out! Closing this now.
