### ISSUE TITLE
setenv.bat suggestion (and manual installation/relocation on windows)

### ISSUE THREAD

**Issue by toschug** [wxphp/wxphp#88]
Small suggestion for setenv.bat:
Changing the `set Path=...` to:
`set Path=%~dp0php;%Path%`

This would have some advantages:
1. Swapping the arguments: `wxphp` would be first found in the wxPHP php dir (what we want), not somewhere else in the path.
2. `%~dp0`: This will work regardless of the install dir. You wouldnt have to touch this file during installation - and during manual installation/relocation (as in: take from orginal install dir and move/copy all to another dir).

I dont see any caveats at the moment.

BTW:
For anyone searching for manual installation/relocation (maybe add this to docs?): 
The other file I had to touch for relocation was the `php.ini`:
`extension_dir="C:\path\to\relocation\php\ext"`
I also removed `unins000.exe` and `unins000.dat` at the new location,
because I assumed they would deinstall the original installation.

Thanks,
toschug

**Comment by jgmdev** [comment]
pull request welcome with the improvement, everything related with windows installer is here https://github.com/wxphp/wxphp/tree/master/tools/inno_setup

**Comment by toschug** [comment]
Pull request done.
I cannot fully test setup.php here, but it should be safe.
I suggest testing with some test build/installation to make sure.
This is my first commit/pull request ever, so bear with me if sth goes wrong with that.

**Comment by jgmdev** [comment]
Thanks! Now you are missing going to https://github.com/wxphp/wxphp/pulls and pressing new pull request, then you should be able to send changes from your wxphp repo to the official wxphp repo for me to merge.
