### ISSUE TITLE
wxTAB_TRAVERSAL within wxPanel

### ISSUE THREAD

**Issue by davekimble2** [wxphp/wxphp#89]
I have a wxFrame with a wxNotebook, and on each tab there is a wxPanel with wxTAB_TRAVERSAL set, and with in that there are a number of buttons and a wxFlexGridSizer.
My expectation was that pressing TAB would cycle through the buttons and then the "cells" of the Grid.

It does cycle through buttons and the cells of the first row of the grid, but on Ubuntu(64) it stops there, and on Ubuntu(32) it goes into a loop consuming 100% CPU.

```
<?php
$window = new wxFrame(null, wxID_TOP, "test", wxDefaultPosition, wxDefaultSize, wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL );
$vbox  = new wxBoxSizer(wxVERTICAL);
	$notebook = new wxNotebook($window, wxID_ANY );
		$panel0 = new wxPanel($notebook, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
			$gbox0 = new wxFlexGridSizer(2, 2, 5, 5);
				$label01 = new wxStaticText($panel0, wxID_ANY, "Name");
			$gbox0->Add($label01, 0, wxALL, 5);
				$namebox = new wxTextCtrl($panel0, wxID_ANY, "", wxDefaultPosition, new wxSize(200, 26) );
			$gbox0->Add($namebox, 0, wxALL, 5);
				$label02 = new wxStaticText($panel0, wxID_ANY, "Email");
			$gbox0->Add($label02, 0, wxALL, 5);
				$emailbox = new wxTextCtrl($panel0, wxID_ANY, "", wxDefaultPosition, new wxSize(200, 26) );
			$gbox0->Add($emailbox, 0, wxALL, 5);
		$panel0->SetSizer($gbox0);
	$notebook->InsertPage(0, $panel0, "A", true );
$vbox->Add($notebook, 1, wxEXPAND|wxALL, 5);
$window->SetSizer($vbox);
$window->Show();
wxEntry();
?>

**Comment by davekimble2** [comment]
Actually Ubuntu(64) does start looping after a while if it is still the active window.  It seems to be 4 processes: php, ibus-daemon, ibus-x11, ibus-engine-simple taking over all 4 cores and using ~75% of CPU time.

**Comment by jgmdev** [comment]
I'm trying to reproduce here on archlinux with your code sample, but haven't been able to. Is there something special I should do?

**Comment by davekimble2** [comment]
Ubuntu 14.04 (64) on quad core hardware.
On wxEntry() the highlighting should be on the A tab. 
Press TAB and the highlight shifts to the first wxTextCtrl() OK. 
Press TAB again and the looping starts.  
On launching Task Manager, the looping stops, but if Task Manager is already running and visible, you can see the processes involved - ibus-daemon using 14% of 4 cores, (56% of one core).  
If Task Manager becomes the active window, the looping stops and the highlighting shifts to the second wxTextCtrl() OK.  
If test.wxphp becomes the active window again, and Press TAB again, and the looping starts again.
Make test.wxphp not the active window, the looping stops and the highlighting cycles to the A tab again.
It seems to be the cycling within the wxFlexGridSizer() that causes it, not the Notebook tabs and not buttons.

On a single core Ubuntu 14.04 (32) machine the CPU usage is 100%.

**Comment by jgmdev** [comment]
Done, can't reproduce. Maybe you are experiencing a kernel threading or pthreads issues. Try updating your kernel or running the sample with: taskset -c 0,2 php sample.wxphp (to limit the process to 2 cores) and see what happens. As final resource you could try fully upgrading your system.

Here are some of my specs
CPU: AMD FX(tm)-8320 Eight-Core Processor
Kernel: Linux 3.19.3-3-ARCH #1 SMP PREEMPT x86_64 GNU/Linux
PHP: 5.6.8 nts (non thread safety)
GTK: gtk+-3.0 (v3.16.2), gtk+-2.0 (v2.24.27)
wxGTK: v3.0.2 -> linked to gtk 3
wxPHP: Latest compiled from github (aka: v3.0.2.0)

**Comment by davekimble2** [comment]
> Maybe you are experiencing a kernel threading or pthreads issues - seems possible. 
Kernel: Linux 3.13.0-49-generic (x86_64) - I don't want to change that.

I tried:
$ taskset -c 0,2 "php ./apps/test/tab.wxphp"
taskset: executing php ./apps/test/tab.wxphp failed: No such file or directory
Format?

I have another test app running which does the same thing:
```
<?php
$window = new wxFrame(null, wxID_TOP, "test2", wxDefaultPosition, wxDefaultSize, wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL );
$hbox  = new wxBoxSizer(wxHORIZONTAL);
	$text1 = new wxTextCtrl($window, wxID_ANY, "");
$hbox->Add($text1, 0, wxALL, 0);
	$text2 = new wxTextCtrl($window, wxID_ANY, "");
$hbox->Add($text2, 0, wxALL, 0);
	$text3 = new wxTextCtrl($window, wxID_ANY, "");
$hbox->Add($text3, 0, wxALL, 0);
$window->SetSizer($hbox);
$window->Show();
wxEntry();
?>

**Comment by jgmdev** [comment]
Tested that other sample code and it still doesn't reproduces here after several tab iterations. My advice would be to **apt-get update && apt-get upgrade** since old libraries may contain bugs and the dependency on other libraries could be kind of huge, so it could be hard to debug. Are you running under wayland?

In any case what desktop environment are you using? I'm using latest XFCE v4.12 with compositing turned up on xserver v1.17.1. I also have gnome 3.16 installed so I will give it a try on it.

**Comment by davekimble2** [comment]
Ubuntu 14.04 is LTS while 14.10 and 15.04 are 9 months only.
Upgrades have never worked well for me.
X not Wayland.
LXDE with window manager OpenBox-3

It seems that wxTAB_TRAVERSAL is part of wxDEFAULT_FRAME_STYLE and can be omitted.
If I replace the textboxes with buttons it works fine, and if I mix both together, it loops on leaving the first textbox. If I interupt it, the highlighted object is the next textbox, not the next object.
So I think that suggests wxWidgets is passing a malformed request to Xorg via ibus-daemon, and not interpreting the response properly.
It's not wxPHP anyway :-)

**Comment by jgmdev** [comment]
Is your wxWidgets (wxgtk) linked against gtk 2 or 3? If 2 you could try building it for gtk 3 and see if that helps. That may also reveal a wxWidgets issue.

**Comment by davekimble2** [comment]
I use your .deb package.

I should just mention that SHIFT+TAB has the same problem, and there's
also a problem with pasting into text boxes sometimes - nothing appears
and it starts looping, and when I raise another window, the looping
stops and the text appears.

**Comment by jgmdev** [comment]
it seems I modified the config.m4 to explicitly build for gtk 3 ( https://github.com/wxphp/wxphp/blob/master/config.m4#L155 ), but I'm not sure if I did that ubuntu .deb build before doing so (checking the commit log got lost), in any case I downloaded the .deb while typing this and did a 
ldd usr/lib/php5/20121212/wxwidgets.so | grep gtk from which I got libgtk-x11-2.0.so.0 so it seems that version of the extension is linked against gtk 3, right now I'm upgrading my lubuntu 14.04 virtual machine to then try and do fresh build of wxPHP. Will comment again when it is ready.

**Comment by jgmdev** [comment]
I finished (may have missed something) doing the modifications required for next release v3.0.2.0 as debian rules to now use gtk3, and just uploaded an ubuntu 14.04 64bits build that links gtk3 

http://sourceforge.net/projects/wxphp/files/wxphp/3.0.2.0/Ubuntu%2014.04/php5-wxwidgets_3.0.2.0_amd64.deb/download

Let me know if that solves your loop issues.

**Comment by davekimble2** [comment]
Thanks for that.
No, it doesn't solve the problem.

PHP 5.5.9
wxPHP 3.0.2.0
wxWidgets 3.0.2

**Comment by jgmdev** [comment]
X_X I just tested your sample code on my lubuntu 14.04 virtual machine and I was able to reproduce, I'm gonna try installing XFCE to see if it's only lxde related,

**Comment by jgmdev** [comment]
Same issue happens with Xfce under ubuntu 14.04 and I can't reproduce the bug on Archlinux which is more up to date, also that wxphp ubuntu build is using latest wxWidgets 3.2.0 as gtk3 so the issue might isn't on wxWidgets but as you pointed out ibus-daemon.

There seems like other people had issues with ibus-daemon and what fixes it is killing the process killall ibus-daemon 

http://askubuntu.com/questions/490317/how-can-i-find-out-what-ibus-daemon-and-ibus-ui-gtk3-are-doing

After killing that process I can confirm your sample code works correctly when pressing tab.

**Comment by davekimble2** [comment]
I can confirm that fixes it.
On LXDE : Menu > Preferences > Language Support > Language > Keyboard
input method = none
should make it permanent, and good riddance - it should never have been
the default setting anyway.

Many thanks once again.
