### ISSUE TITLE
php CLI scripts start crashing in crontab

### ISSUE THREAD

**Issue by shinguz** [wxphp/wxphp#90]
When the following Line is added to /etc/php5/cli/php.ini:
extension = wxwidgets.so

php crontab scripts start crashing with the following stack trace:

Subject: Cron <root@master> /.../fpmmm/bin/fpmmm.php --config=/etc/zabbix/fpmmm.conf >/dev/null
Content-Type: text/plain; charset=ANSI_X3.4-1968
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
Date: Wed, 29 Apr 2015 08:39:02 +0200 (CEST)
Status: RO
08:39:01: Error: Unable to initialize GTK+, is DISPLAY set properly?
(php:7701): GLib-GObject-WARNING **: invalid (NULL) pointer instance
(php:7701): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(php:7701): GLib-GObject-WARNING **: invalid (NULL) pointer instance
(php:7701): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(php:7701): Gdk-CRITICAL **: IA__gdk_screen_get_default_colormap: assertion 'GDK_IS_SCREEN (screen)' failed
(php:7701): Gdk-CRITICAL **: IA__gdk_colormap_get_visual: assertion 'GDK_IS_COLORMAP (colormap)' failed
(php:7701): Gdk-CRITICAL **: IA__gdk_screen_get_default_colormap: assertion 'GDK_IS_SCREEN (screen)' failed
(php:7701): Gdk-CRITICAL **: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
(php:7701): Gdk-CRITICAL **: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
(php:7701): Gdk-CRITICAL **: IA__gdk_window_new: assertion 'GDK_IS_WINDOW (parent)' failed
Segmentation fault (core dumped)

This application does NOT use any wxphp stuff. It was used for test on an other application.

This is a reproducible case at will. Please let me know when you need further information...

**Comment by shinguz** [comment]
Forgot to mention:

uname -a
Linux master 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
lsb_release -a
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty

**Comment by jgmdev** [comment]
The problem is that the script is executed without a xserver instance running which is required for the wxphp extension to properly initialize even if not used which is causing the crash.

In any case new ubuntu deb files include a /usr/bin/wxphp that you can use to launch wxwidgets scripts instead of plain php. So would recommend to disable wxwidgets.so from php.ini and use the wxphp launcher instead.

**Comment by shinguz** [comment]
Thanks for your fast reply.
OK. Got it and already thought it is something like this. No uncommon problem. But should the wxphp not exit/abort a bit more nicely (with a dummy prove error message)...?

**Comment by jgmdev** [comment]
Yep, maybe a more proper message can be thrown or some flag set up in case of exception to prevent library initialization by overriding wxAppConsole::OnExceptionInMainLoop

**Comment by jgmdev** [comment]
As said above, recommended solution is to keep the php.ini clean from wxwidgets.so and use separate /usr/bin/wxphp when required, which does the following:

```sh
#!/bin/sh
exec /usr/bin/php -d extension=wxwidgets.so "$@"
```
