### ISSUE TITLE
Error when compiled with thread safety

### ISSUE THREAD

**Issue by chrisnharvey** [wxphp/wxphp#94]
When I try to use wxPHP on a PHP install compiled with thread safety, I get the following error:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php56/5.6.7/lib/php/extensions/no-debug-zts-20131226/wxwidgets.so' - dlopen(/usr/local/Cellar/php56/5.6.7/lib/php/extensions/no-debug-zts-20131226/wxwidgets.so, 9): Symbol not found: __Z13zif_php_wxC2DiP12_zval_structPS0_S0_iPPPv
  Referenced from: /usr/local/Cellar/php56/5.6.7/lib/php/extensions/no-debug-zts-20131226/wxwidgets.so
  Expected in: flat namespace
 in /usr/local/Cellar/php56/5.6.7/lib/php/extensions/no-debug-zts-20131226/wxwidgets.so in Unknown on line 0
```

**Comment by chrisnharvey** [comment]
My bad. I think I missed ```--with-wxwidgets-macosx```when configuring.

**Comment by jgmdev** [comment]
whats the output of uname -a under macosx? maybe I can automate mac detection on the config.m4 script.

**Comment by chrisnharvey** [comment]
Darwin Chris.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

I usually just check for Darwin in the uname output to detect OS X. Seems to work.

**Comment by jgmdev** [comment]
Haven't tested this but it should work, let me know if you are able to test.
