### ISSUE TITLE
SetDropTarget causes error after application was closed

### ISSUE THREAD

**Issue by mikbox74** [wxphp/wxphp#98]
When SetDropTarget used on any window or control instance it causes error after quit:
![02](https://cloud.githubusercontent.com/assets/1404546/8018919/0d4f629a-0c45-11e5-8ef6-512f0e663cf7.jpg)
The message appeads after a few seconds since pressing close button.
No PHP errors or notices in cmd.
OS: Windows XP SP3
PHP: 5.4.41 with threads
wxWidgets: 3.0.0.2

**Comment by jgmdev** [comment]
Thanks for reporting this error. The cause was the wxDropTarget object was being destroyed by the PHP garbage collector but this is already done by the owner of wxDropTarget which is set when calling $owner->SetDropTarget($drop_target_object)

**Comment by mikbox74** [comment]
Thank you very much for fix, very pleased to know it!
How soon it will be included into official downloadable installers and PECL libraries?

**Comment by jgmdev** [comment]
Thats a good question. Before publishing to pecl I would like to talk with the pecl windows builds maintainer to update wxWidgets libraries from 3.0.1 to 3.0.2. I lost my build environment for windows also, so I have to setup that. I have been struggling to make a release but I will try to do it in the coming days.

Hopefully ydk2 is working on helper scripts for building wxphp in a portable way https://github.com/wxphp/build-scripts which should help for people wanting to deploy their applications.

**Comment by jgmdev** [comment]
Binary builds now available on https://sourceforge.net/projects/wxphp/files/wxphp/3.0.2.0/ also released on pecl http://pecl.php.net/package/wxwidgets (waiting for dll builds to finish), now what is missing, the macosx builds...

**Comment by mikbox74** [comment]
It's fine, thank you!
